/**
 * useOpplan — derives OPPLAN state from streaming agent events.
 *
 * Uses toolArgs (structured data from LLM tool calls) instead of regex
 * parsing, following the same pattern as write_todos / parseTodos.
 *
 * - list_objectives: full table replace (content parsing — full state sync)
 * - add_objective: toolArgs for fields, ID from content
 * - update_objective: toolArgs.objective_id + toolArgs.status directly
 */

import { useMemo } from "react";
import type { AgentEvent } from "../types.js";
import { parseObjectives, type ObjectiveItem } from "../components/ObjectiveList.js";

export interface OpplanState {
  engagement: string;
  objectives: ObjectiveItem[];
}

/** OPPLAN tool names that carry state updates. */
const OPPLAN_TOOLS = new Set([
  "list_objectives",
  "add_objective",
  "update_objective",
]);

export function useOpplan(events: AgentEvent[]): OpplanState | null {
  return useMemo(() => {
    let state: OpplanState | null = null;

    for (const event of events) {
      if (event.type !== "tool_result") continue;
      if (!event.toolName || !OPPLAN_TOOLS.has(event.toolName)) continue;

      const args = event.toolArgs ?? {};

      switch (event.toolName) {
        // ── Full state sync (content parsing — markdown table) ──────
        case "list_objectives": {
          const { objectives, engagement } = parseObjectives(event.content);
          if (objectives.length > 0) {
            state = { engagement, objectives };
          }
          break;
        }

        // ── Add: toolArgs for fields, ID extracted from content ─────
        case "add_objective": {
          const title = args.title as string | undefined;
          const phase = args.phase as string | undefined;
          const priority = args.priority as number | undefined;
          if (!title) break;

          // ID is auto-generated by middleware — extract from result
          const idMatch = event.content.match(/OBJ-\d+/);
          if (!idMatch) break;

          const obj: ObjectiveItem = {
            id: idMatch[0],
            title,
            phase: phase ?? "",
            status: "pending",
            priority: priority ?? 0,
          };

          if (!state) {
            const eng = (args.engagement_name as string) ?? "";
            state = { engagement: eng, objectives: [] };
          } else if (args.engagement_name) {
            state = { engagement: args.engagement_name as string, objectives: state.objectives };
          }

          // state is guaranteed non-null after the block above
          const cur = state as OpplanState;
          const idx = cur.objectives.findIndex((o) => o.id === obj.id);
          if (idx >= 0) {
            state = {
              engagement: cur.engagement,
              objectives: [
                ...cur.objectives.slice(0, idx),
                obj,
                ...cur.objectives.slice(idx + 1),
              ],
            };
          } else {
            state = {
              engagement: cur.engagement,
              objectives: [...cur.objectives, obj],
            };
          }
          break;
        }

        // ── Update: read directly from toolArgs (no regex) ──────────
        case "update_objective": {
          if (!state) break;
          const id = args.objective_id as string | undefined;
          if (!id) break;

          const newStatus = args.status as string | undefined;
          const newOwner = args.owner as string | undefined;
          if (!newStatus && !newOwner) break;

          const current: OpplanState = state;
          state = {
            engagement: current.engagement,
            objectives: current.objectives.map((o: ObjectiveItem) =>
              o.id === id
                ? {
                    ...o,
                    ...(newStatus && { status: newStatus }),
                    ...(newOwner && { owner: newOwner }),
                  }
                : o,
            ),
          };
          break;
        }
      }
    }

    return state;
  }, [events]);
}
